# Generated by Django 4.0.5 on 2022-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
