# Generated by Django 4.0.5 on 2022-07-13 10:39

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chorespost_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='city',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chorespost',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=2, max_length=63),
            preserve_default=False,
        ),
    ]
