# Generated by Django 4.0.5 on 2022-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_chorespost_date_of_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='date_of_post1',
            field=models.DateField(auto_now=True),
        ),
    ]
