# Generated by Django 4.0.5 on 2022-07-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_chorespost_date_of_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorespost',
            name='date_of_post1',
        ),
    ]
