# Generated by Django 4.0.5 on 2022-07-18 13:30

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_remove_chorespost_city_remove_chorespost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='city',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chorespost',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=123, max_length=63),
            preserve_default=False,
        ),
    ]
