# Generated by Django 4.0.5 on 2022-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_remove_chorespost_city_remove_chorespost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='category',
            field=models.CharField(choices=[('1', 'Vodoinstaleter'), ('2', 'Eelektricar')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
