# Generated by Django 4.0.5 on 2022-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0016_alter_chorespost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorespost',
            name='category',
            field=models.CharField(choices=[('1', 'Vodoinstalater\\ka'), ('2', 'Eelektricar\\ka')], max_length=100),
        ),
    ]
