# Generated by Django 4.1 on 2022-08-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0020_chorespost_user_of_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
