# Generated by Django 4.1 on 2022-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0022_alter_chorespost_bio_alter_chorespost_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorespost',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chorespost',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chorespost',
            name='category',
            field=models.CharField(choices=[('1', 'Vodoinstalater\\ka'), ('2', 'Eelektricar\\ka'), ('3', 'Moler\\ka'), ('4', 'Stolar\\ka'), ('5', 'IT'), ('6', 'Zidar\\ka'), ('7', 'Cistac\\ica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chorespost',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
