# Generated by Django 4.1 on 2022-08-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0023_alter_chorespost_bio_alter_chorespost_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorespost',
            name='category',
            field=models.CharField(choices=[('Vodoinstalater\\ka', 'Vodoinstalater\\ka'), ('Eelektricar\\ka', 'Eelektricar\\ka'), ('Moler\\ka', 'Moler\\ka'), ('tolar\\ka', 'Stolar\\ka'), ('IT', 'IT'), ('Zidar\\ka', 'Zidar\\ka'), ('Cistac\\ica', 'Cistac\\ica')], max_length=100),
        ),
    ]
