# Generated by Django 4.1 on 2022-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0024_alter_chorespost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorespost',
            name='category',
            field=models.CharField(choices=[('1', 'Vodoinstalater\\ka'), ('2', 'Eelektricar\\ka'), ('3', 'Moler\\ka'), ('4', 'Stolar\\ka'), ('5', 'IT'), ('6', 'Zidar\\ka'), ('7', 'Cistac\\ica')], max_length=100),
        ),
    ]
