# Generated by Django 4.1 on 2022-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0025_alter_chorespost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorespost',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
