# Generated by Django 4.1 on 2022-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0026_chorespost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorespost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
