# Generated by Django 4.0.5 on 2022-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsusers',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Worker'), ('2', 'Owner')], max_length=100),
        ),
    ]
