# Generated by Django 4.0.5 on 2022-07-19 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientsusers_bio_clientsusers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsusers',
            name='email',
            field=models.EmailField(max_length=300, validators=[django.core.validators.RegexValidator(message='please enter the correct format', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
    ]
