# Generated by Django 4.1 on 2022-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientsusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsusers',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
