# Generated by Django 4.1 on 2022-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clientsusers_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsusers',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
