# Generated by Django 4.1 on 2022-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientsusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsusers',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Worker'), ('2', 'Owner')], max_length=10),
        ),
    ]
