# Generated by Django 4.1 on 2022-08-31 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clienteducationandwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientEducationAndWork',
            new_name='UserEducation',
        ),
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100, null=True)),
                ('start_date_work', models.DateField(null=True)),
                ('end_date_work', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
