# Generated by Django 4.1 on 2022-08-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_clienteducationandwork_usereducation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducation',
            old_name='education',
            new_name='education_high_school',
        ),
        migrations.RenameField(
            model_name='usereducation',
            old_name='end_date_education',
            new_name='end_date_high_school',
        ),
        migrations.RenameField(
            model_name='usereducation',
            old_name='start_date_education',
            new_name='end_date_university',
        ),
        migrations.RenameField(
            model_name='userworkexperience',
            old_name='end_date_work',
            new_name='end_date_experience1',
        ),
        migrations.RenameField(
            model_name='userworkexperience',
            old_name='start_date_work',
            new_name='end_date_experience2',
        ),
        migrations.RenameField(
            model_name='userworkexperience',
            old_name='work',
            new_name='experience1',
        ),
        migrations.AddField(
            model_name='usereducation',
            name='education_university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='start_date_high_school',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='start_date_university',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='end_date_experience3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='end_date_experience4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='experience2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='experience3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='experience4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='start_date_experience1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='start_date_experience2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='start_date_experience3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='start_date_experience4',
            field=models.DateField(null=True),
        ),
    ]
