# Generated by Django 4.1 on 2022-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_education_usereducation_education_high_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkexperience',
            name='start_date_experience2',
            field=models.DateField(default=None, null=True),
        ),
    ]
